# Generated by Django 3.2.5 on 2021-07-25 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Pub',
        ),
    ]
